### ISSUE TITLE
Can't access html from .hbs file

### ISSUE THREAD

**Issue by ilmisantiagobernabeu** [ddbrown30/foundry-family-feud#1]
I tried that earlier, the result was I couldn't access it.

**Comment by ddbrown30** [comment]
I need way more information than this. You've told me basically nothing here. Is this an error message your receiving? What are your repro steps?

**Comment by ilmisantiagobernabeu** [comment]
Can't convert from .hbs file to html file

**Comment by ddbrown30** [comment]
Okay, I'm going to try this one more time before I close the issue. What does that mean and how are you reproducing the bug? Is that an error message you're receiving? If so, how are you triggering it? Where are you seeing it? Can you provide me a screenshot?

I cannot help you without more information.

**Comment by ilmisantiagobernabeu** [comment]
nothing
